theme: minima
title: Houda's lab
author: Houda Kaddioui
email: houda.kaddioui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is mainly my lab notebook as I learn how to apply AI to medical projects. 
  Feel free to reach out to me if you have shared interests or would like to chat.
  
# social links
twitter_username: sha3kouka # DO NOT include the @ character, or else the build will fail!
github_username:  joydisette # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
